services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      composer install && 
      npm install && 
      npm run build &&
      php artisan migrate:fresh --seed --force
    startCommand: php artisan serve
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: myapp_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: myapp_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: myapp_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: myapp_db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: myapp_db
          property: password

databases:
  - name: myapp_db
    plan: free
    ipAllowList: []